services:
  tg_emailer-telegram-bot:
    image: tg_emailer-telegram-bot
    env_file:
      - .env                
    environment:             
      - TELEGRAM_TOKEN
      - EMAIL
      - PASSWORD
      - RECIPIENT
      - SMTP_SERVER
      - SMTP_PORT
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
